### ISSUE TITLE
bwa-memx_index meme wrapper expects specific file name?

### ISSUE THREAD

**Issue by Phlya** [snakemake/snakemake-wrappers#1344]
From what I can tell, the wrapper bwa-memx/index in case of bwa=bwa-meme expects one of the output to be named exactly as {input[0]}.suffixarray_uint64. This file is produced by the first indexing step, and then this exact name is used by the second step. It's is clear from the code of the wrapper: https://github.com/snakemake/snakemake-wrappers/blob/a23858aa5e6980e559ee8cb02f0a54208af9eef5/bio/bwa-memx/index/wrapper.py#L77

Same thing in the bwa-meme wrapper btw: https://github.com/snakemake/snakemake-wrappers/blob/a23858aa5e6980e559ee8cb02f0a54208af9eef5/bio/bwa-meme/index/wrapper.py#L48

**Comment by tavareshugo** [comment]
I think `suffixarray = snakemake.input[0]` should be replaced by `suffixarray = snakemake.output[0]`.

That way, we would have the flexibility of naming the output files in any way desirable. 
For example, at the moment, if the output directory is different from the input FASTA file, `bwa-meme-train-prmi` throws an error because it cannot find the `.suffixarray_uint64` file.

**Comment by fgvieira** [comment]
If someone can make a PR with the suggested changes, I can look into it.

**Comment by tavareshugo** [comment]
@fgvieira I've submitted PR #3303, if you have some time to review. Thanks!

**Comment by fgvieira** [comment]
Just merged it.
Thanks @tavareshugo for your contribution.
