### ISSUE TITLE
STAR wrapper allowing different output names

### ISSUE THREAD

**Issue by supermaxiste** [snakemake/snakemake-wrappers#1740]
**Is your feature request related to a problem?**
I'm currently using the STAR wrapper to align reads from the same sample to two different assemblies and I'd like the outputs to land in the same sample folder. To have different filenames for the two alignments, I'd need to use the option `--outFileNamePrefix`, but currently this is already set to `{tmpdir}/` and adding `--outFileNamePrefix` to `params.extra` leads to the following error:

```
EXITING: FATAL INPUT ERROR: duplicate parameter "outFileNamePrefix" in input "Command-Line-Initial"
SOLUTION: keep only one definition of input parameters in each input source
```

**Describe the solution you'd like**
It would be great to overwrite the default `--outFileNamePrefix` when it's specified in `params.extra`.

**Comment by fgvieira** [comment]
`--outFileNamePrefix` is set to `{tmpdir}/` so that all of `STAR` outpus go to a temp folder and only the outputs specified in the rule are copied to their final destination.

If you want to map your reads against two different reference genomes, you can call the wrapper twice (one for each reference) and set the output to the same sample folder (with diff name depending on the reference).

**Comment by supermaxiste** [comment]
Thank you for the quick reply @fgvieira!

To make sure I understand correctly: does that mean that I can define any name in the `output` and they will be renamed automatically?

**Comment by supermaxiste** [comment]
Tested my question and the answer is yes. Thank you again for the help!
